version: "2"

run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - asciicheck
    - bodyclose
    - dogsled
    - dupl
    - durationcheck
    - errorlint
    - exhaustive
    - copyloopvar
    - forcetypeassert
    - goconst
    - gocritic
    - gocyclo
    - gosec
    - govet
    - ineffassign
    - makezero
    - misspell
    - nakedret
    - nilerr
    - nolintlint
    - prealloc
    - predeclared
    - revive
    - staticcheck
    - thelper
    - unconvert
    - unparam
    - unused
    - whitespace
  settings:
    govet:
      enable:
        - shadow
    gocyclo:
      # Set to 15 to enforce better code maintainability and readability.
      # This stricter threshold encourages breaking down complex functions
      # into smaller, more focused helper functions following best practices.
      min-complexity: 15
    gocritic:
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
    revive:
      rules:
        - name: exported
          arguments: [checkPrivateReceivers]
  exclusions:
    rules:
      - path: _test\.go
        linters:
          - dupl
          - gosec
      # Hugo documentation generator needs more permissive permissions for accessibility
      - path: internal/formatter/hugo\.go
        linters:
          - gosec
        text: "G301|G306"

formatters:
  enable:
    - gofmt
    - gofumpt
    - goimports
  settings:
    gofmt:
      simplify: true
    goimports:
      local-prefixes: 
        - github.com/spandigital/mcp-server-dump