version: 2

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    binary: mcp-server-dump
    main: ./cmd/mcp-server-dump
    ldflags:
      - -s -w -X github.com/spandigital/mcp-server-dump/internal/app.version={{.Version}} -X github.com/spandigital/mcp-server-dump/internal/app.commit={{.Commit}} -X github.com/spandigital/mcp-server-dump/internal/app.date={{.Date}}

kos:
  - repositories:
      - ghcr.io/spandigital/mcp-server-dump
    tags:
      - '{{.Tag}}'
      - latest
    bare: true
    preserve_import_paths: false
    base_import_paths: true
    platforms:
      - linux/amd64
      - linux/arm64

archives:
  - name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
    - goos: windows
      formats: [ 'zip' ]
    - goos: linux
      formats: [ 'tar.gz' ]
    - goos: darwin
      formats: [ 'tar.gz' ]

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ incpatch .Version }}-next"

brews:
  - name: mcp-server-dump
    repository:
      owner: spandigital
      name: homebrew-tap
      branch: main
      token: "{{ .Env.TAP_GITHUB_TOKEN }}"
    directory: Formula
    homepage: "https://github.com/spandigital/mcp-server-dump"
    description: "Extract and document MCP server capabilities in various formats"
    license: "MIT"
    skip_upload: auto
    commit_author:
      name: GoReleaser Bot
      email: bot@goreleaser.com
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"
    dependencies:
      - name: git
        type: optional
    test: |
      system "#{bin}/mcp-server-dump", "--help"
    install: |
      bin.install "mcp-server-dump"

scoops:
  - repository:
      owner: spandigital
      name: scoop-bucket
      branch: main
      token: "{{ .Env.SCOOP_GITHUB_TOKEN }}"
    homepage: "https://github.com/spandigital/mcp-server-dump"
    description: "Extract and document MCP server capabilities in various formats"
    license: "MIT"
    skip_upload: auto
    commit_author:
      name: GoReleaser Bot
      email: bot@goreleaser.com
    commit_msg_template: "Scoop update for {{ .ProjectName }} version {{ .Tag }}"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'